import Head from "next/head";
import Link from "next/link";
export default function NotFound() {
  return (
    <>
      <Head>
        <title>Pucharowa liga szóstek 404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gradient-to-r from-blue-300 to-yellow-200">
        <div className="w-9/12 m-auto py-16 min-h-screen flex items-center justify-center">
          <div className="bg-white shadow overflow-hidden sm:rounded-lg pb-8 w-3/4">
            <div className="border-t border-gray-200 text-center pt-8">
              <h1 className="text-9xl font-bold text-black">404</h1>
              <h1 className="text-6xl font-medium py-8 text-black">
                Strona nie została znaleziona
              </h1>
              <p className="text-2xl pb-8 px-12 font-medium text-black">
                Taka strona nie istnieje, spróbuj jeszcze raz...
              </p>
              <Link
                href="/"
                className="bg-gradient-to-r from-blue-400 to-gray-500 hover:from-gray-500 hover:to-blue-500 text-white font-semibold px-6 py-3 rounded-md mr-6"
              >
                Powrót
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
