import Head from "next/head";
import ReconstructionPage from "./Reconstruction/Reconstruction";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pucharowa liga szóstek - Strona w trakcie przygotowywania</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReconstructionPage />
    </>
  );
}
